### ISSUE TITLE
Incorrect Exception thrown when executing DoubleClassReplacement.parseDouble()

### ISSUE THREAD

**Issue by jgaleotti** [EMResearch/EvoMaster#104]
DoubleClassReplacement.parseDouble("0..0") should throw NumberFormatException instead of IllegalArgumentException. 
The following test case fails:

```
@Test
    public void testParseSuccessDoubleDot() {
        String inputString = "0..0";
        assertThrows(NumberFormatException.class, () -> {
            DoubleClassReplacement.parseDouble(inputString, ObjectiveNaming.METHOD_REPLACEMENT + "IdTemplate");
        });
    }
```

**Comment by jgaleotti** [comment]
Related to this problem, in LongClassReplacement.parseLong(String) if the input string has 20 digits but it is greater than Long.MAX_VALUE, it signals an IllegalArgumentException instead of the expected NumberFormatException.
For example:
`
    @Test
    public void testParseClassReplacement() {
        BigInteger bigInteger = BigInteger.valueOf(Long.MAX_VALUE).add(BigInteger.ONE);
        String input = bigInteger.toString();
        assertThrows(NumberFormatException.class, () -> {
            LongClassReplacement.parseLong(input, ObjectiveNaming.METHOD_REPLACEMENT + "IdTemplate");
        });
    }
`

**Comment by arcuri82** [comment]
Hi,
 recall from `for_developers.md`:

"Trello... Issues/bugs: reported bugs which are not trivial to fix. For developers, better to report them here than GitHub issue page."

:)

**Comment by jgaleotti** [comment]
Thanks. I will move these issues to the Trello
