### ISSUE TITLE
[ERROR] ERROR in the Remote EvoMaster Driver: Failed to start the system under test

### ISSUE THREAD

**Issue by QuanQuanoooooo** [EMResearch/EvoMaster#143]
Hi!
After I successfully compiled EMB and EvoMaster, I run EmbeddedEvoMasterController.java then there are the following warning:
**SLF4J: The requested version 1.7.16 by your slf4j binding is not compatible with [1.6]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.**
22:56:24.761 [main] DEBUG shaded.org.eclipse.jetty.util.log - Logging to Logger[shaded.org.eclipse.jetty.util.log] via shaded.org.eclipse.jetty.util.log.Slf4jLog
22:56:24.803 [main] INFO shaded.org.eclipse.jetty.util.log - Logging initialized @2475ms to shaded.org.eclipse.jetty.util.log.Slf4jLog
22:56:24.939 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - Server@3aeaafa6{STOPPED}[9.4.z-SNAPSHOT] added {QueuedThreadPool[qtp243745864]@e874448{STOPPED,8<=0<=200,i=0,q=0}[shaded.org.eclipse.jetty.util.thread.TryExecutor$$Lambda$35/352359770@569cfc36],AUTO}
22:56:25.210 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - HttpConnectionFactory@5fcd892a[HTTP/1.1] added {HttpConfiguration@8b87145{32768/8192,8192/8192,https://:0,[]},POJO}
22:56:25.235 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - ServerConnector@43d7741f{null,[]}{0.0.0.0:0} added {Server@3aeaafa6{STOPPED}[9.4.z-SNAPSHOT],UNMANAGED}
22:56:25.239 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - ServerConnector@43d7741f{null,[]}{0.0.0.0:0} added {QueuedThreadPool[qtp243745864]@e874448{STOPPED,8<=0<=200,i=0,q=0}[shaded.org.eclipse.jetty.util.thread.TryExecutor$$Lambda$35/352359770@569cfc36],AUTO}
22:56:25.244 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - ServerConnector@43d7741f{null,[]}{0.0.0.0:0} added {ScheduledExecutorScheduler@15bfd87{STOPPED},AUTO}
22:56:25.245 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - ServerConnector@43d7741f{null,[]}{0.0.0.0:0} added {shaded.org.eclipse.jetty.io.ArrayByteBufferPool@17baae6e,POJO}
22:56:25.247 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - ServerConnector@43d7741f{null,[http/1.1]}{0.0.0.0:0} added {HttpConnectionFactory@5fcd892a[HTTP/1.1],AUTO}
22:56:25.247 [main] DEBUG shaded.org.eclipse.jetty.server.AbstractConnector - ServerConnector@43d7741f{HTTP/1.1,[http/1.1]}{0.0.0.0:0} added HttpConnectionFactory@5fcd892a[HTTP/1.1]
22:56:25.260 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - ServerConnector@43d7741f{HTTP/1.1,[http/1.1]}{0.0.0.0:0} added {SelectorManager@ServerConnector@43d7741f{HTTP/1.1,[http/1.1]}{0.0.0.0:0},MANAGED}
22:56:25.261 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - Server@3aeaafa6{STOPPED}[9.4.z-SNAPSHOT] added {ServerConnector@43d7741f{HTTP/1.1,[http/1.1]}{localhost:40100},AUTO}
22:56:25.303 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - Server@3aeaafa6{STOPPED}[9.4.z-SNAPSHOT] added {ErrorHandler@76b10754{STOPPED},AUTO}
22:56:25.804 [main] DEBUG shaded.org.eclipse.jetty.util.DecoratedObjectFactory - Adding Decorator: shaded.org.eclipse.jetty.util.DeprecationWarning@4ac3c60d
22:56:25.805 [main] WARN shaded.org.eclipse.jetty.server.handler.ContextHandler - s.o.e.j.s.ServletContextHandler@4facf68f{/,null,UNAVAILABLE} contextPath ends with /*
22:56:25.817 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - Server@3aeaafa6{STOPPED}[9.4.z-SNAPSHOT] added {s.o.e.j.s.ServletContextHandler@4facf68f{/controller/api,null,UNAVAILABLE},MANAGED}
22:56:25.829 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - s.o.e.j.s.ServletContextHandler@4facf68f{/controller/api,null,UNAVAILABLE} added {ServletHandler@3d51f06e{STOPPED},MANAGED}
22:56:25.831 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - ServletHandler@3d51f06e{STOPPED} added {shaded.org.glassfish.jersey.servlet.ServletContainer-15d9bc04@ac5cdb83==shaded.org.glassfish.jersey.servlet.ServletContainer,jsp=null,order=-1,inst=true,AUTO}
22:56:25.833 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - ServletHandler@3d51f06e{STOPPED} added {[/*]=>shaded.org.glassfish.jersey.servlet.ServletContainer-15d9bc04,POJO}
22:56:25.834 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting Server@3aeaafa6{STOPPED}[9.4.z-SNAPSHOT]
22:56:25.878 [main] INFO shaded.org.eclipse.jetty.server.Server - jetty-9.4.z-SNAPSHOT; built: 2018-08-30T13:59:14.071Z; git: 27208684755d94a92186989f695db2d7b21ebc51; jvm 1.8.0_181-b13
22:56:25.942 [main] DEBUG shaded.org.eclipse.jetty.server.handler.AbstractHandler - starting Server@3aeaafa6{STARTING}[9.4.z-SNAPSHOT]
22:56:25.945 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting QueuedThreadPool[qtp243745864]@e874448{STOPPED,8<=0<=200,i=0,q=0}[shaded.org.eclipse.jetty.util.thread.TryExecutor$$Lambda$35/352359770@569cfc36]
22:56:25.952 [main] DEBUG shaded.org.eclipse.jetty.util.thread.ReservedThreadExecutor - ReservedThreadExecutor@6973b51b{s=0/4,p=0}
22:56:25.953 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - QueuedThreadPool[qtp243745864]@e874448{STARTING,8<=0<=200,i=0,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}] added {ReservedThreadExecutor@6973b51b{s=0/4,p=0},AUTO}
22:56:25.955 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting ReservedThreadExecutor@6973b51b{s=0/4,p=0}
22:56:25.965 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @3639ms ReservedThreadExecutor@6973b51b{s=0/4,p=0}
22:56:25.969 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @3643ms QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=8,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}]
22:56:25.969 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting ErrorHandler@76b10754{STOPPED}
22:56:25.970 [main] DEBUG shaded.org.eclipse.jetty.server.handler.AbstractHandler - starting ErrorHandler@76b10754{STARTING}
22:56:25.971 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @3646ms ErrorHandler@76b10754{STARTED}
22:56:25.972 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting s.o.e.j.s.ServletContextHandler@4facf68f{/controller/api,null,UNAVAILABLE}
22:56:26.005 [main] DEBUG shaded.org.eclipse.jetty.http.PreEncodedHttpField - HttpField encoders loaded: [shaded.org.eclipse.jetty.http.Http1FieldPreEncoder@1aa7ecca]
22:56:26.126 [main] DEBUG shaded.org.eclipse.jetty.server.handler.AbstractHandler - starting s.o.e.j.s.ServletContextHandler@4facf68f{/controller/api,null,STARTING}
22:56:26.127 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting ServletHandler@3d51f06e{STOPPED}
22:56:26.165 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHandler - Path=/*[EMBEDDED:null] mapped to servlet=shaded.org.glassfish.jersey.servlet.ServletContainer-15d9bc04[EMBEDDED:null]
22:56:26.170 [main] DEBUG shaded.org.eclipse.jetty.http.pathmap.PathMappings - Added MappedResource[pathSpec=ServletPathSpec["/*",pathDepth=1,group=PREFIX_GLOB],resource=shaded.org.glassfish.jersey.servlet.ServletContainer-15d9bc04@ac5cdb83==shaded.org.glassfish.jersey.servlet.ServletContainer,jsp=null,order=-1,inst=true] to PathMappings[size=1]
22:56:26.170 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHandler - filterNameMap={}
22:56:26.170 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHandler - pathFilters=null
22:56:26.170 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHandler - servletFilterMap=null
22:56:26.171 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHandler - servletPathMap=PathMappings[size=1]
22:56:26.171 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHandler - servletNameMap={shaded.org.glassfish.jersey.servlet.ServletContainer-15d9bc04=shaded.org.glassfish.jersey.servlet.ServletContainer-15d9bc04@ac5cdb83==shaded.org.glassfish.jersey.servlet.ServletContainer,jsp=null,order=-1,inst=true}
22:56:26.171 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHandler - Adding Default404Servlet to ServletHandler@3d51f06e{STARTING}
22:56:26.173 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - ServletHandler@3d51f06e{STARTING} added {shaded.org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-36902638@44b13e60==shaded.org.eclipse.jetty.servlet.ServletHandler$Default404Servlet,jsp=null,order=-1,inst=false,AUTO}
22:56:26.173 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - ServletHandler@3d51f06e{STARTING} added {[/]=>shaded.org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-36902638,POJO}
22:56:26.173 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHandler - Path=/*[EMBEDDED:null] mapped to servlet=shaded.org.glassfish.jersey.servlet.ServletContainer-15d9bc04[EMBEDDED:null]
22:56:26.174 [main] DEBUG shaded.org.eclipse.jetty.http.pathmap.PathMappings - Added MappedResource[pathSpec=ServletPathSpec["/*",pathDepth=1,group=PREFIX_GLOB],resource=shaded.org.glassfish.jersey.servlet.ServletContainer-15d9bc04@ac5cdb83==shaded.org.glassfish.jersey.servlet.ServletContainer,jsp=null,order=-1,inst=true] to PathMappings[size=1]
22:56:26.174 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHandler - Path=/[EMBEDDED:null] mapped to servlet=shaded.org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-36902638[EMBEDDED:null]
22:56:26.174 [main] DEBUG shaded.org.eclipse.jetty.http.pathmap.PathMappings - Added MappedResource[pathSpec=ServletPathSpec["/",pathDepth=-1,group=DEFAULT],resource=shaded.org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-36902638@44b13e60==shaded.org.eclipse.jetty.servlet.ServletHandler$Default404Servlet,jsp=null,order=-1,inst=false] to PathMappings[size=2]
22:56:26.175 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHandler - filterNameMap={}
22:56:26.184 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHandler - pathFilters=null
22:56:26.184 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHandler - servletFilterMap=null
22:56:26.184 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHandler - servletPathMap=PathMappings[size=2]
22:56:26.185 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHandler - servletNameMap={shaded.org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-36902638=shaded.org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-36902638@44b13e60==shaded.org.eclipse.jetty.servlet.ServletHandler$Default404Servlet,jsp=null,order=-1,inst=false, shaded.org.glassfish.jersey.servlet.ServletContainer-15d9bc04=shaded.org.glassfish.jersey.servlet.ServletContainer-15d9bc04@ac5cdb83==shaded.org.glassfish.jersey.servlet.ServletContainer,jsp=null,order=-1,inst=true}
22:56:26.186 [main] DEBUG shaded.org.eclipse.jetty.server.handler.AbstractHandler - starting ServletHandler@3d51f06e{STARTING}
22:56:26.187 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @3861ms ServletHandler@3d51f06e{STARTED}
22:56:26.188 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting shaded.org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-36902638@44b13e60==shaded.org.eclipse.jetty.servlet.ServletHandler$Default404Servlet,jsp=null,order=-1,inst=false
22:56:26.191 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @3865ms shaded.org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-36902638@44b13e60==shaded.org.eclipse.jetty.servlet.ServletHandler$Default404Servlet,jsp=null,order=-1,inst=false
22:56:26.191 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting shaded.org.glassfish.jersey.servlet.ServletContainer-15d9bc04@ac5cdb83==shaded.org.glassfish.jersey.servlet.ServletContainer,jsp=null,order=-1,inst=true
22:56:26.191 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @3866ms shaded.org.glassfish.jersey.servlet.ServletContainer-15d9bc04@ac5cdb83==shaded.org.glassfish.jersey.servlet.ServletContainer,jsp=null,order=-1,inst=true
22:56:26.196 [main] DEBUG shaded.org.eclipse.jetty.servlet.ServletHolder - Servlet.init shaded.org.glassfish.jersey.servlet.ServletContainer@7f0eb4b4 for shaded.org.glassfish.jersey.servlet.ServletContainer-15d9bc04
**Jan 09, 2020 10:56:28 PM shaded.org.glassfish.jersey.internal.inject.Providers checkProviderRuntime
警告: A provider org.evomaster.client.java.controller.internal.EMController registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.evomaster.client.java.controller.internal.EMController will be ignored.** 
22:56:29.487 [main] INFO shaded.org.eclipse.jetty.server.handler.ContextHandler - Started s.o.e.j.s.ServletContextHandler@4facf68f{/controller/api,null,AVAILABLE}
22:56:29.487 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @7161ms s.o.e.j.s.ServletContextHandler@4facf68f{/controller/api,null,AVAILABLE}
22:56:29.487 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting ServerConnector@43d7741f{HTTP/1.1,[http/1.1]}{localhost:40100}
22:56:29.533 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - ServerConnector@43d7741f{HTTP/1.1,[http/1.1]}{localhost:40100} added {sun.nio.ch.ServerSocketChannelImpl[/127.0.0.1:40100],POJO}
22:56:29.535 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting ScheduledExecutorScheduler@15bfd87{STOPPED}
22:56:29.536 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @7210ms ScheduledExecutorScheduler@15bfd87{STARTED}
22:56:29.536 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting HttpConnectionFactory@5fcd892a[HTTP/1.1]
22:56:29.537 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @7211ms HttpConnectionFactory@5fcd892a[HTTP/1.1]
22:56:29.540 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting SelectorManager@ServerConnector@43d7741f{HTTP/1.1,[http/1.1]}{localhost:40100}
22:56:29.578 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - EatWhatYouKill@2237bada/SelectorProducer@2472c7d8/IDLE/p=false/QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=8,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-01-09T22:56:29.572+08:00 added {SelectorProducer@2472c7d8,POJO}
22:56:29.582 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - EatWhatYouKill@2237bada/SelectorProducer@2472c7d8/IDLE/p=false/QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=8,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-01-09T22:56:29.582+08:00 added {QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=8,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}],UNMANAGED}
22:56:29.585 [main] DEBUG shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill - EatWhatYouKill@2237bada/SelectorProducer@2472c7d8/IDLE/p=false/QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=8,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-01-09T22:56:29.585+08:00 created
22:56:29.588 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - ManagedSelector@62b3df3a{STOPPED} id=0 keys=-1 selected=-1 updates=0 added {EatWhatYouKill@2237bada/SelectorProducer@2472c7d8/IDLE/p=false/QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=8,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-01-09T22:56:29.588+08:00,MANAGED}
22:56:29.589 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - SelectorManager@ServerConnector@43d7741f{HTTP/1.1,[http/1.1]}{localhost:40100} added {ManagedSelector@62b3df3a{STOPPED} id=0 keys=-1 selected=-1 updates=0,AUTO}
22:56:29.590 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - EatWhatYouKill@420745d7/SelectorProducer@7e11ab3d/IDLE/p=false/QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=8,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-01-09T22:56:29.59+08:00 added {SelectorProducer@7e11ab3d,POJO}
22:56:29.593 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - EatWhatYouKill@420745d7/SelectorProducer@7e11ab3d/IDLE/p=false/QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=8,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-01-09T22:56:29.593+08:00 added {QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=8,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}],UNMANAGED}
22:56:29.594 [main] DEBUG shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill - EatWhatYouKill@420745d7/SelectorProducer@7e11ab3d/IDLE/p=false/QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=8,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-01-09T22:56:29.594+08:00 created
22:56:29.595 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - ManagedSelector@5fa47fea{STOPPED} id=1 keys=-1 selected=-1 updates=0 added {EatWhatYouKill@420745d7/SelectorProducer@7e11ab3d/IDLE/p=false/QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=8,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-01-09T22:56:29.594+08:00,MANAGED}
22:56:29.595 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - SelectorManager@ServerConnector@43d7741f{HTTP/1.1,[http/1.1]}{localhost:40100} added {ManagedSelector@5fa47fea{STOPPED} id=1 keys=-1 selected=-1 updates=0,AUTO}
22:56:29.595 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting ManagedSelector@62b3df3a{STOPPED} id=0 keys=-1 selected=-1 updates=0
22:56:29.596 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting EatWhatYouKill@2237bada/SelectorProducer@2472c7d8/IDLE/p=false/QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=8,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-01-09T22:56:29.595+08:00
22:56:29.596 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @7270ms EatWhatYouKill@2237bada/SelectorProducer@2472c7d8/IDLE/p=false/QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=8,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-01-09T22:56:29.596+08:00
22:56:29.606 [main] DEBUG shaded.org.eclipse.jetty.util.thread.QueuedThreadPool - queue shaded.org.eclipse.jetty.io.ManagedSelector$$Lambda$190/1531175283@28f8e165
22:56:29.606 [qtp243745864-11] DEBUG shaded.org.eclipse.jetty.util.thread.QueuedThreadPool - run shaded.org.eclipse.jetty.io.ManagedSelector$$Lambda$190/1531175283@28f8e165
22:56:29.607 [main] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - Queued change shaded.org.eclipse.jetty.io.ManagedSelector$Start@545f80bf on ManagedSelector@62b3df3a{STARTING} id=0 keys=0 selected=0 updates=0
22:56:29.607 [qtp243745864-11] DEBUG shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill - EatWhatYouKill@2237bada/SelectorProducer@2472c7d8/IDLE/p=false/QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=7,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-01-09T22:56:29.607+08:00 tryProduce false
22:56:29.611 [qtp243745864-11] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - updateable 1
22:56:29.612 [qtp243745864-11] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - update shaded.org.eclipse.jetty.io.ManagedSelector$Start@545f80bf
22:56:29.612 [qtp243745864-11] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - updates 0
22:56:29.612 [qtp243745864-11] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - Selector sun.nio.ch.KQueueSelectorImpl@3404bbdf waiting with 0 keys
22:56:29.614 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @7288ms ManagedSelector@62b3df3a{STARTED} id=0 keys=0 selected=0 updates=0
22:56:29.614 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting ManagedSelector@5fa47fea{STOPPED} id=1 keys=-1 selected=-1 updates=0
22:56:29.615 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - starting EatWhatYouKill@420745d7/SelectorProducer@7e11ab3d/IDLE/p=false/QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=7,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-01-09T22:56:29.615+08:00
22:56:29.615 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @7289ms EatWhatYouKill@420745d7/SelectorProducer@7e11ab3d/IDLE/p=false/QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=7,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-01-09T22:56:29.615+08:00
22:56:29.616 [main] DEBUG shaded.org.eclipse.jetty.util.thread.QueuedThreadPool - queue shaded.org.eclipse.jetty.io.ManagedSelector$$Lambda$190/1531175283@66f66866
22:56:29.616 [qtp243745864-12] DEBUG shaded.org.eclipse.jetty.util.thread.QueuedThreadPool - run shaded.org.eclipse.jetty.io.ManagedSelector$$Lambda$190/1531175283@66f66866
22:56:29.616 [qtp243745864-12] DEBUG shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill - EatWhatYouKill@420745d7/SelectorProducer@7e11ab3d/IDLE/p=false/QueuedThreadPool[qtp243745864]@e874448{STARTED,8<=8<=200,i=6,q=0}[ReservedThreadExecutor@6973b51b{s=0/4,p=0}][pc=0,pic=0,pec=0,epc=0]@2020-01-09T22:56:29.616+08:00 tryProduce false
22:56:29.616 [qtp243745864-12] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - updateable 0
22:56:29.617 [qtp243745864-12] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - updates 0
22:56:29.617 [qtp243745864-12] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - Selector sun.nio.ch.KQueueSelectorImpl@406b977e waiting with 0 keys
22:56:29.618 [main] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - Queued change shaded.org.eclipse.jetty.io.ManagedSelector$Start@22fa55b2 on ManagedSelector@5fa47fea{STARTING} id=1 keys=0 selected=0 updates=0
22:56:29.618 [main] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - Wakeup on submit ManagedSelector@5fa47fea{STARTING} id=1 keys=0 selected=0 updates=1
22:56:29.626 [qtp243745864-12] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - Selector sun.nio.ch.KQueueSelectorImpl@406b977e woken with none selected
22:56:29.627 [qtp243745864-12] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - Selector sun.nio.ch.KQueueSelectorImpl@406b977e woken up from select, 0/0/0 selected
22:56:29.627 [qtp243745864-12] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - Selector sun.nio.ch.KQueueSelectorImpl@406b977e processing 0 keys, 1 updates
22:56:29.627 [qtp243745864-12] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - updateable 1
22:56:29.627 [qtp243745864-12] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - update shaded.org.eclipse.jetty.io.ManagedSelector$Start@22fa55b2
22:56:29.627 [qtp243745864-12] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - updates 0
22:56:29.627 [qtp243745864-12] DEBUG shaded.org.eclipse.jetty.io.ManagedSelector - Selector sun.nio.ch.KQueueSelectorImpl@406b977e waiting with 0 keys
22:56:29.627 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @7301ms ManagedSelector@5fa47fea{STARTED} id=1 keys=0 selected=0 updates=0
22:56:29.627 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @7302ms SelectorManager@ServerConnector@43d7741f{HTTP/1.1,[http/1.1]}{localhost:40100}
22:56:29.629 [main] DEBUG shaded.org.eclipse.jetty.util.component.ContainerLifeCycle - ServerConnector@43d7741f{HTTP/1.1,[http/1.1]}{localhost:40100} added {acceptor-0@30f4b1a6,POJO}
22:56:29.630 [main] DEBUG shaded.org.eclipse.jetty.util.thread.QueuedThreadPool - queue acceptor-0@30f4b1a6
22:56:29.630 [qtp243745864-13] DEBUG shaded.org.eclipse.jetty.util.thread.QueuedThreadPool - run acceptor-0@30f4b1a6
22:56:29.631 [main] INFO shaded.org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@43d7741f{HTTP/1.1,[http/1.1]}{localhost:40100}
22:56:29.634 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @7307ms ServerConnector@43d7741f{HTTP/1.1,[http/1.1]}{localhost:40100}
22:56:29.635 [main] INFO shaded.org.eclipse.jetty.server.Server - Started @7309ms
22:56:29.636 [main] DEBUG shaded.org.eclipse.jetty.util.component.AbstractLifeCycle - STARTED @7310ms Server@3aeaafa6{STARTED}[9.4.z-SNAPSHOT]
Started controller server on: http://localhost:40100/controller/api
![image](https://user-images.githubusercontent.com/33426645/72078281-c6ce9f00-3333-11ea-8e2b-1ce14f3c0311.png)
Then I ran EvoMaster and had a problem.
* EvoMaster version: 1.0.0
Jan 09, 2020 10:48:52 PM org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor aroundWriteTo: MessageBodyWriter not found for media type=application/json, type=class org.evomaster.client.java.controller.api.dto.SutRunDto, genericType=class org.evomaster.client.java.controller.api.dto.SutRunDto.
22:48:52.659 [main] WARN  o.e.c.r.service.RemoteController - Failed to connect to SUT: MessageBodyWriter not found for media type=application/json, type=class org.evomaster.client.java.controller.api.dto.SutRunDto, genericType=class org.evomaster.client.java.controller.api.dto.SutRunDto.
* [ERROR] ERROR in the Remote EvoMaster Driver: Failed to start the system under test
  Look at the logs of the EvoMaster Driver to help debugging this problem.

I don't know which part is wrong, I hope to get your help.

**Comment by arcuri82** [comment]
Hi,
 which system in EMB are you trying? 

Furthermore, a clarification: EvoMaster can use either JDK 8 or 11, but EMB must use 8

is there any logs after the
```
Started controller server on: http://localhost:40100/controller/api
```
?

**Comment by arcuri82** [comment]
The documentation of EMB now clearly states that JDK 8 is required.

As no further info was provided, I cannot replicate this issue, so I ll have to close it.
