### ISSUE TITLE
Confused about ports in EmbeddedEvoMasterController

### ISSUE THREAD

**Issue by mado89** [EMResearch/EvoMaster#169]
Hi,
I have a question about the EmbeddedEvoMasterController. What is the meaning of the port parameter? It seems to be ignored.
Take https://github.com/EMResearch/EMB/blob/master/em/embedded/rest/news/src/main/java/em/embedded/org/tsdes/EmbeddedEvoMasterController.java for example. 
* In line 29 a local variable port is declared but seems to be unused. 
* Since in Line 52 0 is passed as parameter. https://github.com/EMResearch/EMB/blob/9f769ffab5d5c3e8836c1bae6354863adee316ca/em/embedded/rest/ncs/src/main/java/em/embedded/org/restncs/EmbeddedEvoMasterController.java#L52

Am I missing something here?

https://github.com/openjournals/joss-reviews/issues/2153

**Comment by arcuri82** [comment]
Hi,
 it is not ignored :) Somehow, this is briefly discussed in the [documentation](https://github.com/EMResearch/EvoMaster/blob/master/docs/write_driver.md): "When starting the SUT, there are at least two configurations that you want to change: the binding port, as you want to use 0 for ephemeral ports (to avoid port conflicts)".

You can learn more about it by googling for "ephemeral port" and "tcp port 0".

Also from the documentation:

```
The actual chosen port can then be extracted with:

protected int getSutPort() {
        return (Integer) ((Map) ctx.getEnvironment()
                .getPropertySources().get("server.ports").getSource())
                .get("local.server.port");
}
```

Do you think we should add some more info on what ephemeral ports are?

**Comment by arcuri82** [comment]
I guess here also a possible source of confusion is that there are 2 ports involved:
- the one of EvoMaster driver itself (default 40100, but that can be changed from command-line)
- the one of the SUT (System Under Test), which should be ephemeral

**Comment by mado89** [comment]
Yes that was the confusion

**Comment by arcuri82** [comment]
ok, fair enough :) I ll add some more documentation about it

**Comment by arcuri82** [comment]
hi,
 do the documentation changes in #171 clarify it? Or should I add some more info?
