### ISSUE TITLE
Qualitity of the Paper

### ISSUE THREAD

**Issue by mado89** [EMResearch/EvoMaster#170]
Hi,

while (for now) I do not see much which would hinder an acceptance of the software I'd like to have some major improvements on the paper itself.

Main points (so far)
* Referenced literature consists of self citations only
* Statement of need / Addressed research question does not come through (for me)
* No related work / state of field at all (see first point)
* From what I can see you did quite some benchmarking. I'd like a summary of your results to be featured in the paper. Something along the lines of "When I let it run for the suggested 24h (black box testing), can I use my computer meanwhile or do I have to run it on a different machine?". 

https://github.com/openjournals/joss-reviews/issues/2153

**Comment by arcuri82** [comment]
Hi,
 thanks. I updated the paper, addressing your first 3 points. However, I am not sure about your last one: "When I let it run for the suggested 24h (black box testing), can I use my computer meanwhile or do I have to run it on a different machine?"
That all depends on the hardware: ie, how many cores and how much RAM is available (and network connection in case of black-box testing of a remote service). It also  depends on the system under test (e.g., does it use a database?). 
We currently do not have any published data on timing in respect to the hardware involved (all experiments run so far were based on number of HTTP calls, to abstract from all the issues of doing analyses that are time and hardware dependent).

**Comment by s0nata** [comment]
Hi, I'll join this discussion with remarks on the paper quality on my end:

Statement of Need section:
- [ ] paragraph 2: "... techniques aimed at automating several different tasks in **SE**" --> did you mean "in testing"?
- [ ] do you think you could reformulate the sentence about the potential research users? To me it seems too vague for its current length (just shortening is fine).

Tool Summary section, paragraph 2:
- [ ] could you maybe list a couple examples of the challenges you refer to?
- [ ] it is not clear to me from the text if `EvoMaster` incorporates the techniques listed, or was used as an auxiliary tool in  experiments. It is also a bit odd to read about publications in the section that describes tool functionalities. If there was an explicit list of basic and additional functionalities of the tool, I would have found it helpful both in understanding what the tool does and how it compares to the competition.

References:
- [ ] could you please consistently provide DOIs/links to cited publications?

[openjournals/joss-reviews#2153](https://github.com/openjournals/joss-reviews/issues/2153)

**Comment by arcuri82** [comment]
@s0nata: thanks for the feedback. I tried to address all of your concerns, and updated the paper accordingly. Let me know if some parts are still unclear, and/or if you require further clarifications and modifications.

**Comment by s0nata** [comment]
@arcuri82 looks great, thanks! One last minor point: "Statement of need" section, paragraph 2 sentence 2: "To address this problem, in SE ... in SE" - the second "in SE" reference in the same sentence seems redundant. Could you please take it out?

**Comment by arcuri82** [comment]
@s0nata: thanks for spotting that issue. it is fixed now

**Comment by arcuri82** [comment]
closed as JOSS paper has been accepted
