### ISSUE TITLE
Whitebox Testing

### ISSUE THREAD

**Issue by mado89** [EMResearch/EvoMaster#177]
Hi,

I wanted to follow https://github.com/EMResearch/EvoMaster/blob/master/docs/write_driver.md to create a driver to test your framework using an application I have written. 

Some comments / questions (I will add more once they arise): 

- [x] Is it correct that I have to download a different software than "evomaster.jar" from github? Using "evomaster.jar" the package "org.evomaster.client.java.controller" is missing. 
- [ ] authentication: Could you please provide a link or some information on how to implement 'getInfoForAuthentication'

Thanks!

openjournals/joss-reviews#2153

**Comment by arcuri82** [comment]
hi,
 thx. you are indeed correct. but u do not download it from GitHub, you download it from Maven Central with Maven/Gradle. 
I added a clarification to `write_driver.md`

**Comment by mado89** [comment]
Thanks. The instructions are much clearer now.
I guess what is missing now is some information on how to provide the authentication. I am currently testing your framework against an application of mine. Most end points are secured using oauth. Hence, it would be nice to have this information.

**Comment by arcuri82** [comment]
we have basic support for some kinds of authentication. OAuth is unfortunately not among them :(  we will support it in the future, but it will take several months before we have time to add it (it is not in the current priorities)

anyway, I will add some documentation on how security is currently handled (eg, clarify that OAuth is not supported at the moment)

btw, is you are application open-source? if yes, it would be an interesting case study for when we will support OAuth

**Comment by arcuri82** [comment]
I now added more info on security at [https://github.com/EMResearch/EvoMaster/blob/master/docs/write_driver.md]()

**Comment by arcuri82** [comment]
closed as JOSS paper has been accepted
