### ISSUE TITLE
Closing database in  features-service 

### ISSUE THREAD

**Issue by qixin5** [EMResearch/EvoMaster#210]
Dear EvoMaster's authors,

Thanks for making the tool and benchmark available!

I used EvoMaster to have test cases generated for features-service (based on the embedded controller you provided). Later I ran these test cases but failed to pass all of them. I appreciate any comments/clues/help that can guide me on fixing this. In the attachment, you can find the command I used and the log I got. Thank you in advance!
[materials.tar.gz](https://github.com/EMResearch/EvoMaster/files/5505425/materials.tar.gz)

**Comment by arcuri82** [comment]
Hi,
  you wrote 

> failed to pass all of them

but in that gz file  you wrote:

> It fails to pass two of the test cases: test_24 and test_25. 

Which one is which? if a couple of tests fail, that is known problem (see *Known limitations* in the documentation). But if they all fail, that's different

Regarding:
> Also, there is a problem with closing the database in the end. Please see log.txt for details.

that is not really a problem. it is just a warning that we try to close a database that is already closed. but it happened at the end after all tests are already finished

**Comment by qixin5** [comment]
Hi @arcuri82,

Thanks for your reply!

Sorry, what I meant is that it doesn't pass all of them and fails for the two. So I guess it's a known problem (although I didn't see this using the external controller).

**Comment by arcuri82** [comment]
moved to https://github.com/EMResearch/EMB/issues/23
