### ISSUE TITLE
NPE when running EmbeddedSutController extended file

### ISSUE THREAD

**Issue by marshallia** [EMResearch/EvoMaster#236]
Hi @arcuri82 ,
I've written the java class extends with EmbeddedSutController but when I try to run it I got the NPE exception (in this line InstrumentedSutStarter starter = new InstrumentedSutStarter(controller)). My code is a simple program without a database connection.

`public class EvoMasterController extends EmbeddedSutController {
    private ConfigurableApplicationContext ctx;
    private final int port;
    private Connection connection;
    public static void main(String[] args) {
        int port = 40100;
        EvoMasterController controller = new EvoMasterController(port);
        InstrumentedSutStarter starter = new InstrumentedSutStarter(controller);
        starter.start();
    }
    public EvoMasterController(int port) {
        this.port = port;
    }

    @Override
    public boolean isSutRunning() {
        return ctx !=null && ctx.isRunning();
    }
    @Override
    public String getPackagePrefixesToCover() {
        return null;
    }
    @Override
    public List<AuthenticationDto> getInfoForAuthentication() {
        return null;
    }
    @Override
    public Connection getConnection() {
        return null;
    }
    @Override
    public String getDatabaseDriverName() {
        return null;
    }
    @Override
    public ProblemInfo getProblemInfo() {
        return null;
    }

    @Override
    public SutInfoDto.OutputFormat getPreferredOutputFormat() {
        return null;
    }
    @Override
    public String startSut() {
        ctx = SpringApplication.run(DemoApplication.class, new String[]{"--server.port=0"});
        return "http://localhost:"+getSutPort();
    }
    @Override
    public void stopSut() {
        ctx.stop();
    }
    @Override
    public void resetStateOfSUT() {
    }
    protected int getSutPort(){
        return (Integer)((Map) ctx.getEnvironment().getPropertySources().get("server.port").getSource())
                .get("local.server.port");
    }`
Is there may relation with the unresolved ea in InstrumentedSutStarter?
![Screenshot from 2021-01-15 16-26-37](https://user-images.githubusercontent.com/12694360/104700828-b8d60a00-574f-11eb-89d0-690160842ba4.png)
Thank you,,

**Comment by arcuri82** [comment]
Hi,
 thx for reporting this issue. We indeed need to provide better error messages... :)
I can see at least these problems in your configuration: `getProblemInfo()`,  `getPackagePrefixesToCover()` and `getPreferredOutputFormat()` __MUST__ return valid info

**Comment by marshallia** [comment]
Thank you for your reply @arcuri82. The problem has solved. I'll close this issue.
