### ISSUE TITLE
not able to imprort evomaster.org to a new swagger system error with EMDriver 

### ISSUE THREAD

**Issue by webrollygoal** [EMResearch/EvoMaster#247]

**Comment by arcuri82** [comment]
this issue has no info... please provide some description :)

**Comment by webrollygoal** [comment]
?[0m
* EvoMaster version: 1.1.0
16:47:26.041 [main] WARN  o.e.c.r.service.RemoteController - Failed to change running state of the SUT. HTTP status 500. Error: 'Failed to start bean 'documentationPluginsBootstrappe
r'; nested exception is java.lang.NoSuchMethodError: org.springframework.plugin.core.PluginRegistry.getPluginFor(Ljava/lang/Object;)Ljava/util/Optional;'
* ?[31m[ERROR] ?[0m?[33mERROR in the Remote EvoMaster Driver: Failed to start the system under test
  Look at the logs of the EvoMaster Driver to help debugging this problem.?[0m

same problem on compiling the evomaster on the code

**Comment by arcuri82** [comment]
Hi,
  googling that error message gives this [SO question](https://stackoverflow.com/questions/59703461/nosuchmethoderror-org-springframework-plugin-core-pluginregistry-getpluginordef).
Looks like some dependency issue on your SpringBoot application.

And which version of JVM are you using? 8? 11?

**Comment by webrollygoal** [comment]
JVM 1.8

**Comment by webrollygoal** [comment]
Hi, I am running a Spring boot 2.2.0 with swagger version 2.9.2 and in swagger configuration file if I am using @configuration and @EnableSwagger2, getting the following error:

APPLICATION FAILED TO START

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

springfox.documentation.spring.web.plugins.DocumentationPluginsManager.createContextBuilder(DocumentationPluginsManager.java:152)
The following method did not exist:

org.springframework.plugin.core.PluginRegistry.getPluginFor(Ljava/lang/Object;Lorg/springframework/plugin/core/Plugin;)Lorg/springframework/plugin/core/Plugin;
The method's class, org.springframework.plugin.core.PluginRegistry, is available from the following locations:

jar:file:/Users/SystemName/.m2/repository/org/springframework/plugin/spring-plugin-core/2.0.0.M1/spring-plugin-core-2.0.0.M1.jar!/org/springframework/plugin/core/PluginRegistry.class
It was loaded from the following location:

file:/Users/SystemName/.m2/repository/org/springframework/plugin/spring-plugin-core/2.0.0.M1/spring-plugin-core-2.0.0.M1.jar

**Comment by arcuri82** [comment]
Hi,
  you wrote u are using SpringBoot `2.2.0`, but looks like the on classpath you have spring-plugin on `2.0.0.M1`, which leads to this versioning mismatch

**Comment by webrollygoal** [comment]
sir can we please have a short zoom call
I have really important work with this application it will be great help sir

**Comment by webrollygoal** [comment]
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    springfox.documentation.schema.plugins.SchemaPluginsManager.viewProvider(SchemaPluginsManager.java:95)

The following method did not exist:

    org.springframework.plugin.core.PluginRegistry.getPluginFor(Ljava/lang/Object;)Ljava/util/Optional;

The method's class, org.springframework.plugin.core.PluginRegistry, is available from the following locations:

    jar:file:/C:/Users/Hp/.m2/repository/org/springframework/plugin/spring-plugin-core/1.2.0.RELEASE/spring-plugin-core-1.2.0.RELEASE.jar!/org/springframework/plugin/core/PluginRegistry.class

It was loaded from the following location:

    file:/C:/Users/Hp/.m2/repository/org/springframework/plugin/spring-plugin-core/1.2.0.RELEASE/spring-plugin-core-1.2.0.RELEASE.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.plugin.core.PluginRegistry


Process finished with exit code 1

**Comment by arcuri82** [comment]
added a clarification in the documentation regarding trying out:
```
public static void main(String[] args) {
    SpringApplication.run(Application.class, args);
}
```

However, this is a forum to report bugs in EvoMaster, not on solving classpath issues in Spring :(
