### ISSUE TITLE
Help with Output

### ISSUE THREAD

**Issue by webrollygoal** [EMResearch/EvoMaster#256]
Sir can we have a short zoom call I want to extend this work with evomaster and want to understand the working of evomaster as well
also, sir, I'm getting this output can you please explain the parts of this output
Going to save 22 tests to src/test/java

Evaluated tests: 99567
Evaluated actions: 112024
Needed budget: 3%
Passed time (seconds): 600
Execution time per test (ms): Avg=4.80 , min=0.00 , max=1465.00
Computation overhead between tests (ms): Avg=1.22 , min=0.00 , max=107.00
Covered targets (lines, branches, faults, etc.): 69
Potential faults: 26
Bytecode line coverage: NaN% (0 out of 0 in 0 units/classes)
EvoMaster process has completed successfully
What is evaluated tests
what is evaluated actions et

**Comment by arcuri82** [comment]
sorry, but too busy to have yet another zoom call...

regarding your question, we will need to update the documentation. but in short, EM tries out several test cases ("Evaluated tests"), although only a minimized set based on coverage is given as output at the end ("Going to save 22 tests"). Each test case can be composed of 1 or more HTTP calls ("actions"), so "Evaluated actions" >= "Evaluated tests"

**Comment by vaibhavpudke0007** [comment]
Failed to retrieve SUT info. HTTP status 500. Error: 'SQL drivers are misconfigured. You must use a 'p6spy' wrapper when yo
u run the SUT. For example, a database connection URL like 'jdbc:h2:mem:testdb' should be changed into 'jdbc:p6spy:h2:mem:testdb'. See documentation on how to configure P6Spy.'
* ←[31m[ERROR] ←[0m←[33mERROR in the Remote EvoMaster Driver: Failed to retrieve the info about the system under test

**Comment by arcuri82** [comment]
info has now been added here:
https://github.com/EMResearch/EvoMaster/blob/master/docs/console_output.md
