### ISSUE TITLE
postgres integration 

### ISSUE THREAD

**Issue by webrollygoal007** [EMResearch/EvoMaster#263]
how can I integrate Postgres with EMDriver the steps written on https://github.com/EMResearch/EvoMaster/blob/master/docs/write_driver.md

 are not clear for Postgres testing

**Comment by arcuri82** [comment]
hi,
 to improve the documentation, I need you to be more specific with the issue you are having. eg, which parts are not clear?

furthermore, would adding a [link to an example](https://github.com/EMResearch/EvoMaster/blob/master/e2e-tests/spring-rest-postgres/src/test/kotlin/com/foo/spring/rest/postgres/SpringRestPostgresController.kt) be enough?

**Comment by webrollygoal007** [comment]
sir, I'm not using container its a standalone project  
this is my driver   thank you soo much sir for your great help
package org.example;

import com.p6spy.engine.spy.P6SpyDriver;
import io.swagger.Swagger2SpringBoot;
import org.evomaster.client.java.controller.EmbeddedSutController;
import org.evomaster.client.java.controller.InstrumentedSutStarter;
import org.evomaster.client.java.controller.api.dto.AuthenticationDto;
import org.evomaster.client.java.controller.api.dto.SutInfoDto;
import org.evomaster.client.java.controller.db.DbCleaner;
import org.evomaster.client.java.controller.internal.SutController;
import org.evomaster.client.java.controller.problem.ProblemInfo;
import org.evomaster.client.java.controller.problem.RestProblem;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;


import java.sql.Connection;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;


public class EMDriver extends EmbeddedSutController {

    public static void main(String[] args){

        SutController controller = new EMDriver();
        InstrumentedSutStarter starter = new InstrumentedSutStarter(controller);

        starter.start();

         final GenericContainer postgres = new GenericContainer("postgres:9")
                .withExposedPorts(5432)
                .withEnv("POSTGRES_HOST_AUTH_METHOD","trust")
                .withTmpFs(Collections.singletonMap("/var/lib/postgresql/data", "rw"));
    }

    private ConfigurableApplicationContext ctx;
    private Connection connection;

    public boolean isSutRunning() {
        return ctx!=null && ctx.isRunning();
    }

    public String getPackagePrefixesToCover() {
        return "org.example";
    }

    public List<AuthenticationDto> getInfoForAuthentication() {
        return null;
    }

    public Connection getConnection() {
        return connection;
    }

    public String getDatabaseDriverName() {
        return "org.h2.Driver";
    }

    public ProblemInfo getProblemInfo() {
        return new RestProblem("http://localhost:8080/cds-au/v1/api-docs", null);
    }

    public SutInfoDto.OutputFormat getPreferredOutputFormat() {
        return SutInfoDto.OutputFormat.JAVA_JUNIT_5;
    }

    protected int getSutPort() {
        return (Integer) ((Map) ctx.getEnvironment()
                .getPropertySources().get("server.ports").getSource())
                .get("local.server.port");
    }


    public String startSut() {

       postgres.start();
        String host = postgres.getContainerIpAddress();
        int port = postgres.getMappedPort(5432);
        String url = "jdbc:postgresql://localhost:5432/cdr_au";
        //String url = "jdbc:p6spy:postgresql://"+host+":"+port+"/postgres;

        ctx = SpringApplication.run(Swagger2SpringBoot.class, new String[]{
                "--spring.datasource.url=jdbc:p6spy:h2:mem:testdb;DB_CLOSE_DELAY=-1;",
                "--spring.datasource.driver-class-name=" + P6SpyDriver.class.getName(),
                "--spring.jpa.database=cdr_au",
                "--spring.datasource.username=postgres",
                "--spring.datasource.password=root",
                "--spring.jpa.properties.hibernate.show_sql=true",
                "--spring.jpa.hibernate.ddl-auto=validate",
                "--spring.flyway.locations=${pathToFlywayFiles()}",
                "--spring.jmx.enabled=false"
        });

        JdbcTemplate jdbc = ctx.getBean(JdbcTemplate.class);
        try {
            connection = jdbc.getDataSource().getConnection();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }


        return "http://localhost:8080";
    }

    public void stopSut() {
        postgres.stop();
        ctx.stop();
    }

    public void resetStateOfSUT() {
        DbCleaner.clearDatabase_H2(connection);

    }
}











**and this is the error** 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project spring-swagger-codegen-obf: Compilation failure: Compilat
ion failure:
[ERROR] /C:/Users/Hp/Desktop/cdsswaggerdb/src/test/java/org/example/EMDriver.java:[35,16] cannot find symbol
[ERROR]   symbol:   class GenericContainer
[ERROR]   location: class org.example.EMDriver
[ERROR] /C:/Users/Hp/Desktop/cdsswaggerdb/src/test/java/org/example/EMDriver.java:[35,48] cannot find symbol
[ERROR]   symbol:   class GenericContainer
[ERROR]   location: class org.example.EMDriver
[ERROR] /C:/Users/Hp/Desktop/cdsswaggerdb/src/test/java/org/example/EMDriver.java:[81,8] cannot find symbol
[ERROR]   symbol:   variable postgres
[ERROR]   location: class org.example.EMDriver
[ERROR] /C:/Users/Hp/Desktop/cdsswaggerdb/src/test/java/org/example/EMDriver.java:[82,23] cannot find symbol
[ERROR]   symbol:   variable postgres
[ERROR]   location: class org.example.EMDriver
[ERROR] /C:/Users/Hp/Desktop/cdsswaggerdb/src/test/java/org/example/EMDriver.java:[83,20] cannot find symbol
[ERROR]   symbol:   variable postgres
[ERROR]   location: class org.example.EMDriver
[ERROR] /C:/Users/Hp/Desktop/cdsswaggerdb/src/test/java/org/example/EMDriver.java:[111,9] cannot find symbol
[ERROR]   symbol:   variable postgres
[ERROR]   location: class org.example.EMDriver
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by arcuri82** [comment]
sorry, but this is not related to EM, but rather to basic programming. you have an error message about a compilation error that literally tells you cannot find the variable postgres, as u declared it as local variable inside the main function... plus you did not import GenericContainer (added now a clarification about it in the documentation)
