### ISSUE TITLE
error with output on running evomaster jar file

### ISSUE THREAD

**Issue by vaibhavpudke0007** [EMResearch/EvoMaster#266]
Failed to change running state of the SUT. HTTP status 500. Error: 'Error creating bean with name 'org.springframework.boot
.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreat
ionException: Error creating bean with name 'spring.jpa-org.springframework.boot.autoconfigure.orm.jpa.JpaProperties': Could not bind properties to JpaProperties (prefix=spring.jpa, ig
noreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.validation.BindException: org.springframework.boot.bind.Relaxe
dDataBinder$RelaxedBeanPropertyBindingResult: 1 errors
Field error in object 'spring.jpa' on field 'database': rejected value [cdr_au]; codes [typeMismatch.spring.jpa.database,typeMismatch.database,typeMismatch.org.springframework.orm.jpa.
vendor.Database,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [spring.jpa.database,database]; arguments []; default message [datab
ase]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'org.springframework.orm.jpa.vendor.Database' for property 'database'; nested excep
tion is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [org.springframework.orm.jpa.vendor.Database] for value 'cdr_
au'; nested exception is java.lang.IllegalArgumentException: No enum constant org.springframework.orm.jpa.vendor.Database.cdr_au]'
* ?[31m[ERROR] ?[0m?[33mERROR in the Remote EvoMaster Driver: Failed to start the system und

**Comment by arcuri82** [comment]
hi. issue looks like how you start your application, ie misconfiguration of database, and not something related to EvoMaster

**Comment by vaibhavpudke0007** [comment]
Failed to retrieve SUT info. HTTP status 500. Error: 'SQL drivers are misconfigured. You must use a 'p6spy' wrapper when yo
u run the SUT. For example, a database connection URL like 'jdbc:h2:mem:testdb' should be changed into 'jdbc:p6spy:h2:mem:testdb'. See documentation on how to configure P6Spy.'
* ←[31m[ERROR] ←[0m←[33mERROR in the Remote EvoMaster Driver: Failed to retrieve the info about the system under test
