### ISSUE TITLE
How to run EMDriver from command line

### ISSUE THREAD

**Issue by vaibhavpudke0007** [EMResearch/EvoMaster#277]
how to run  this file from common line
package org.example;

import com.p6spy.engine.spy.P6SpyDriver;
import org.evomaster.client.java.controller.EmbeddedSutController;
import org.evomaster.client.java.controller.InstrumentedSutStarter;
import org.evomaster.client.java.controller.api.dto.AuthenticationDto;
import org.evomaster.client.java.controller.api.dto.SutInfoDto;
import org.evomaster.client.java.controller.db.DbCleaner;
import org.evomaster.client.java.controller.internal.SutController;
import org.evomaster.client.java.controller.problem.ProblemInfo;
import org.evomaster.client.java.controller.problem.RestProblem;
import org.songrong.swaggerdemo.SwaggerdemoApplication;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

public class EMDriver extends EmbeddedSutController {

    public static void main(String[] args){

        SutController controller = new EMDriver();
        InstrumentedSutStarter starter = new InstrumentedSutStarter(controller);

        starter.start();
    }

    private ConfigurableApplicationContext ctx;
    private Connection connection;

    public boolean isSutRunning() {
        return ctx!=null && ctx.isRunning();
    }

    public String getPackagePrefixesToCover() {
        return "org.example";
    }

    public List<AuthenticationDto> getInfoForAuthentication() {
        return null;
    }

    public Connection getConnection() {
        return connection;
    }

    public String getDatabaseDriverName() {
        return "org.h2.Driver";
    }

    public ProblemInfo getProblemInfo() {
        return new RestProblem("http://localhost:8080/v2/api-docs", null);
    }

    public SutInfoDto.OutputFormat getPreferredOutputFormat() {
        return SutInfoDto.OutputFormat.JAVA_JUNIT_5;
    }

    public String startSut() {

        ctx = SpringApplication.run(SwaggerdemoApplication.class, new String[]{
                "--spring.datasource.url=jdbc:p6spy:h2:mem:testdb;DB_CLOSE_DELAY=-1;",
                "--spring.datasource.driver-class-name=" + P6SpyDriver.class.getName()
        });

      /* JdbcTemplate jdbc = ctx.getBean(JdbcTemplate.class);
        try {
            connection = jdbc.getDataSource().getConnection();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }*/

        return "http://localhost:8080";
    }

    public void stopSut() {
        ctx.stop();
    }

    public void resetStateOfSUT() {

    }
}

**Comment by arcuri82** [comment]
added following to the documentation:

"Note that it is also possible to run the driver from command-line, like any other Java program with a `main` function.
However, in such case, you will need to package an uber jar file (e.g., using plugins like `maven-shade-plugin` and `maven-assembly-plugin`)."

**Comment by vaibhavpudke0007** [comment]
sir I tried all these steps but still not able to run it commond-line can you please guide step bu step how to run this through command line in Intellij that will be great help

**Comment by arcuri82** [comment]
if you are using IntelliJ, why not just right-click on the file and choose "Run"?

**Comment by vaibhavpudke0007** [comment]
yeah it is running that way but I have integrated with some big projects so I need its commomdline way to do it

**Comment by arcuri82** [comment]
you need to look at the documentation of `maven-shade-plugin`. eg using something like:

```
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <finalName>NAME</finalName>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <manifestEntries>
                                        <Main-Class>EM-DRIVER</Main-Class>
                                        <Can-Redefine-Classes>true</Can-Redefine-Classes>
                                        <Can-Retransform-Classes>true</Can-Retransform-Classes>
                                    </manifestEntries>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```
