### ISSUE TITLE
problem with jar file

### ISSUE THREAD

**Issue by vaibhavpudke0007** [EMResearch/EvoMaster#280]
after building the package ( mvn install package). I have tried the below the command from console
java -cp swaggerdemo-0.0.1-SNAPSHOT.jar org.example.EMDriver
but getting the following error
Error: Could not find or load main class org.example.EMDriver
even i checked that jar file but those file not found... Please kindly check revert back

**Comment by arcuri82** [comment]
building jar files is not related to EM
