### ISSUE TITLE
Unable to run EMDriver on command line

### ISSUE THREAD

**Issue by dkarthi1973** [EMResearch/EvoMaster#281]
I couldn't run EMDriver from console for scripting purpose. 
D:\karthi\workspace\vibhav\ProjectApril9\target\test-classes\org\example>java -cp swaggerdemo-0.0.1-SNAPSHOT.jar org.example.EMDriver
Error: Could not find or load main class org.example.EMDriver

D:\karthi\workspace\vibhav\ProjectApril9\target\test-classes\org\example>java -cp swaggerdemo-0.0.1-SNAPSHOT.jar EMDriver
Error: Could not find or load main class EMDriver

could you please advise us to resolve the issue.

**Comment by arcuri82** [comment]
duplicate of #280
