### ISSUE TITLE
Evomaster -how to use Other features like Client ,Core-IT,core-driver-it

### ISSUE THREAD

**Issue by dkarthi1973** [EMResearch/EvoMaster#288]
We have implemented and running successfully evomaster (core). interesting to experiment other area like client-java, core-graphql-it, could you please share some useful stuff to implement client-java. it will helpful for us.

**Comment by arcuri82** [comment]
sorry, i do not understand your question. you will need to be more specific

**Comment by dkarthi1973** [comment]
how to use/integrate  client-java  from Evomaster project

**Comment by arcuri82** [comment]
https://github.com/EMResearch/EvoMaster/blob/master/docs/write_driver.md
