### ISSUE TITLE
The generated code have exception

### ISSUE THREAD

**Issue by bestdd** [EMResearch/EvoMaster#338]
Use the project named rest-api-example, using evomaster1.2.1.jar. The generated code files EvoMaster_fault_representatives_Test and EvoMaster_faults_Test have exception code. What is the problem?

![image](https://user-images.githubusercontent.com/7333223/124120737-aefa5600-daa6-11eb-951b-88ece8b516c5.png)

![image](https://user-images.githubusercontent.com/7333223/124120466-65117000-daa6-11eb-982f-f29c4b35fd12.png)

**Comment by arcuri82** [comment]
hi.
 thx. weird bug... 

anyway, for now you can avoid it by using `--expectationsActive false`

**Comment by bestdd** [comment]
> hi.
> thx. weird bug...
> 
> anyway, for now you can avoid it by using `--expectationsActive false`

thx

**Comment by arcuri82** [comment]
the bug here is that, for that part of the code related to expectation handling, we are generating the instructions in Kotlin, instead of Java

**Comment by arcuri82** [comment]
this should be now fixed in the new `1.3.0` release
