### ISSUE TITLE
exception with running black box tests in different mac system version

### ISSUE THREAD

**Issue by thinkpadt68** [EMResearch/EvoMaster#340]
hello , I tried to using evomaster for black-box testing in different mac system. Except that the system version is different, the java version is the same, and the project is the same. It can run normally in version 10.15.5, and an error is reported when running in version 11.2.3.

`java -jar /Users/xxx/dev_tools/evomaster1.2.1.jar  --blackBox true --bbSwaggerUrl http://localhost:6060/v2/api-docs  --outputFormat JAVA_JUNIT_4 --maxTime 60s`

`* EvoMaster version: 1.2.1
15:36:23.012 [main] ERROR o.e.c.r.service.RemoteController - EvoMaster Driver process is no longer responding, refusing TCP connections. Check if its process might have crashed. Also look at its logs
15:36:23.013 [main] WARN  o.e.c.r.service.RemoteController - Failed to connect to SUT: java.net.ConnectException: Connection refused (Connection refused)
* [ERROR] EvoMaster process terminated abruptly. This is likely a bug in EvoMaster. Please copy&paste the following stacktrace, and create a new issue on https://github.com/EMResearch/EvoMaster/issues
java.lang.IllegalStateException: Failed to start the SUT
	at org.evomaster.core.Main$Companion.init(Main.kt:233)
	at org.evomaster.core.Main$Companion.initAndRun(Main.kt:140)
	at org.evomaster.core.Main$Companion.main(Main.kt:73)
	at org.evomaster.core.Main.main(Main.kt)`

one mac system version is 10.15.5, another is 11.2.3

**Comment by arcuri82** [comment]
Hi,
 thx for reporting this issue.

This is really weird... that part of the code should not be executed in BB mode. Just to be 100% sure,  when you run it on 11.2.3, you had exactly that command with `--blackBox true`?

**Comment by thinkpadt68** [comment]
yeah ，I'm ok!  I know why it was error.  

`java -jar /Users/xxx/dev_tools/evomaster1.2.1.jar  --blackBox true --bbSwaggerUrl http://localhost:6060/v2/api-docs  --outputFormat JAVA_JUNIT_4 --maxTime 60s` 

In that command, It have many blanks between `--bbSwaggerUrl` and 'http://localhost:6060/v2/api-docs' .

thx for your quick reply!

**Comment by arcuri82** [comment]
the number of blanks should have no impact... anyway, glad to hear it is working now for you
