### ISSUE TITLE
Evomaster only generates fault tests

### ISSUE THREAD

**Issue by huseyinmertkok** [EMResearch/EvoMaster#396]
My code is very similar with your example of [rest-api](https://github.com/EMResearch/rest-api-example).
But EM didn't generate success tests. I used both black and white box testing. I tried different max time values (like 30s,1m,10m,30m) but didn't work. 

Is there any solution for this?

**Comment by huseyinmertkok** [comment]
1.2.1

**Comment by arcuri82** [comment]
hmmmm... I tried now again 1.2.1 on `rest-api-example`, with no issue...

can you clarify what you mean with `didn't generate success tests`? ie, was there no HTTP call at all with returned 2xx status code? 
was there any error/warning in the logs?

without looking at your API, it is hard to tell what is going on :(   it might be some input validation for which we are not able yet to generate valid data for

**Comment by arcuri82** [comment]
this should be now fixed in the new `1.3.0` release
