### ISSUE TITLE
Regarding the "budget" shown in the output.

### ISSUE THREAD

**Issue by Minju-Kan** [EMResearch/EvoMaster#482]
Hi @arcuri82,
Thank you for this interesting tool to learn automation of API test suites.
I would like to know more about the work of Evomaster,
I saw your [docs/console_output.md](https://github.com/EMResearch/EvoMaster/blob/master/docs/console_output.md) , 
then I tried to run the black box test for 10 minutes and 1 hour.
I want to ask you some question about my output.

10 minutes：
```
* Evaluated tests: 110
* Evaluated actions: 604
* Needed budget: 43%
* Passed time (seconds): 604
* Execution time per test (ms): Avg=5490.27 , min=977.00 , max=10081.00
* Computation overhead between tests (ms): Avg=1.65 , min=0.00 , max=11.00
* Successfully executed (HTTP code 2xx) 0 endpoints out of 0 (NaN%)
```

1 hour：
```
* Evaluated tests: 657
* Evaluated actions: 3602
* Needed budget: 15%
* Passed time (seconds): 3604
* Execution time per test (ms): Avg=5485.30 , min=804.00 , max=10063.00
* Computation overhead between tests (ms): Avg=0.96 , min=0.00 , max=11.00
* Successfully executed (HTTP code 2xx) 0 endpoints out of 0 (NaN%)
```

---
1. Is the lower value of "Needed budget" the better? (eg 15% is better than 43%), which range of percentages would you suggest for "Needed budget"?
2. I see that your paper mentions Search Budget(k), may I ask you what is the relationship between Search Budget(k) and Needed Budget(%)?

**Comment by arcuri82** [comment]
Hi.
 I wrote some more documentation. Let me know if anything is still unclear
