### ISSUE TITLE
source code compiler problem

### ISSUE THREAD

**Issue by chenchawei** [EMResearch/EvoMaster#492]
Hi
I downloaded v1.4 of the source code,
Want to add custom fuctions to see more details
But before starting, unable to complier successfully,
It returns an error similar to the following after complied：
Kotlin: Unresolved reference: PostgresLikeBaseVisitor
Kotlin: 'visitPattern' overrides nothing
Kotlin: Unresolved reference: PostgresLikeParser...and more

My environment uses intellij with java version "1.8.0_221",
Kotlin SDK uses IntelliJ IDEA 2021.3.2\plugins,
Also make sure that some other Java Projects can run successfully ,and can use mvn to export jar files,
Black box testing with the Github page provided evomaster.jar also works fine.

Are there any special settings that need to be set when using these source codes?

Hope you have a nice day, thank you so much!

**Comment by arcuri82** [comment]
Hi,

  you need to build it at least once with Maven, as some source files are generated with Maven plugins. If you try to compile directly with an IDE before doing that first step, it will not compile.

I ll update the documentation to clarify it
