### ISSUE TITLE
Error Compiling client-java

### ISSUE THREAD

**Issue by inoex135** [EMResearch/EvoMaster#5]
I got this errors when I tried to run mvn install
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] evomaster-client-java .............................. SUCCESS [  0.403 s]
[INFO] evomaster-client-java-util ......................... SUCCESS [  1.618 s]
[INFO] evomaster-client-java-controller-api ............... SUCCESS [ 17.291 s]
[INFO] evomaster-client-java-instrumentation .............. SUCCESS [  6.023 s]
[INFO] evomaster-client-java-controller ................... FAILURE [ 19.649 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 45.454 s
[INFO] Finished at: 2018-05-14T19:42:23+07:00
[INFO] Final Memory: 39M/756M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.1.0:shade (default) on project evomaster-client-java-controller: Error creating shaded jar: duplicate entry: META-INF/services/shaded.com.fasterxml.jackson.databind.Module -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :evomaster-client-java-controller

**Comment by arcuri82** [comment]
yes, that's known issue related to shader plugin. try to run `mvn clean install` instead

**Comment by inoex135** [comment]
unfortunately I got other errors:

[ERROR] Failures: 
[ERROR]   DbDirectIntEMTest.testRunEM:31->RestTestBase.assertHasAtLeastOne:152 REST calls:
GET /api/db/directint/-397/-781632731 , auth=NoAuth
POST /api/db/directint , auth=NoAuth
 ==> expected: <true> but was: <false>
[ERROR]   HLEMTest.testRunEM:39->RestTestBase.assertHasAtLeastOne:158->RestTestBase.assertHasAtLeastOne:152 REST calls:
PATCH /api/hl/1URDdHnH6t , auth=NoAuth
DELETE /api/hl/6KFc , auth=NoAuth
PUT /api/hl/F_7KFktH , auth=NoAuth
DELETE /api/hl/J , auth=NoAuth
PUT /api/hl/NO_RU , auth=NoAuth
GET /api/hl/wBBS , auth=NoAuth
POST /api/hl , auth=NoAuth
POST /api/hl , auth=NoAuth
PUT /api/hl/F_7KFktl , auth=NoAuth
POST /api/hl , auth=NoAuth
DELETE /api/hl/xz131M2LOjrl2n , auth=NoAuth
POST /api/hl , auth=NoAuth
PATCH /api/hl/_YjEqon5SJ4vfetV , auth=NoAuth
PATCH /api/hl/_YjEqon5SJ4vfetV , auth=NoAuth
POST /api/hl , auth=NoAuth
PATCH /api/hl/_YjEqon5SJ4vfetV , auth=NoAuth
PATCH /api/hl/_YjEqon5SJ4vfetV , auth=NoAuth
 ==> expected: <true> but was: <false>
[ERROR]   NREMTest.testRunEM:42->RestTestBase.assertHasAtLeastOne:158->RestTestBase.assertHasAtLeastOne:152 REST calls:
PATCH /api/nr/NT9P36G446BFv , auth=NoAuth
DELETE /api/nr/7oE3 , auth=NoAuth
POST /api/nr/c1URDdHnH6 , auth=NoAuth
PUT /api/nr/PBwBBSF , auth=NoAuth
PUT /api/nr/1 , auth=NoAuth
PUT /api/nr/fz , auth=NoAuth
POST /api/nr/bRzY26d , auth=NoAuth
GET /api/nr/xZk_49NmfdN , auth=NoAuth
GET /api/nr/sQ , auth=NoAuth
PUT /api/nr/CmCuQ5DK8bX9 , auth=NoAuth
PUT /api/nr/DCRDMQTO5JVpYFh , auth=NoAuth
PATCH /api/nr/VP , auth=NoAuth
PUT /api/nr/mCpTLxJWN15qQCN , auth=NoAuth
PUT /api/nr/Pyh , auth=NoAuth
GET /api/nr/7bsgTq , auth=NoAuth
PUT /api/nr/0DhXFbUe , auth=NoAuth
POST /api/nr/XBOi , auth=NoAuth
POST /api/nr/0lxFU , auth=NoAuth
PATCH /api/nr/0lxFU , auth=NoAuth
POST /api/nr/0lxFU , auth=NoAuth
PATCH /api/nr/0lxFU , auth=NoAuth
POST /api/nr/pfpfL5ajgENg3vt , auth=NoAuth
DELETE /api/nr/pfpfL5ajgENg3vt , auth=NoAuth
POST /api/nr/eE2H3SOJY , auth=NoAuth
GET /api/nr/eE2H3SOJY , auth=NoAuth
POST /api/nr/fRzY22 , auth=NoAuth
GET /api/nr/xZk_49NmfcN , auth=NoAuth
PUT /api/nr/DCRDMQTO5JVpYFh , auth=NoAuth
PATCH /api/nr/R , auth=NoAuth
POST /api/nr/XFIUvwd , auth=NoAuth
PUT /api/nr/mCpTHxJWN/5qQCNf , auth=NoAuth
POST /api/nr/fQzY2 , auth=NoAuth
GET /api/nr/x%5Ck_49NmfcN , auth=NoAuth
PUT /api/nr/MR0V4H , auth=NoAuth
PUT /api/nr/DCRDMQTO5JVpYFh , auth=NoAuth
PUT /api/nr/ZvysX , auth=NoAuth
PATCH /api/nr/R , auth=NoAuth
POST /api/nr/XFIUvwd , auth=NoAuth
POST /api/nr/jQzY2 , auth=NoAuth
GET /api/nr/x%5Ck_49NmfcN , auth=NoAuth
DELETE /api/nr/m , auth=NoAuth
POST /api/nr/jfHJGl4 , auth=NoAuth
DELETE /api/nr/NqUyvEaQsD , auth=NoAuth
PUT /api/nr/Zv%7Bs%5C , auth=NoAuth
PATCH /api/nr/N , auth=NoAuth
POST /api/nr/XFIUvwd , auth=NoAuth
 ==> expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 42, Failures: 3, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] EvoMaster .......................................... SUCCESS [  0.407 s]
[INFO] evomaster-client-java .............................. SUCCESS [  0.012 s]
[INFO] evomaster-client-java-controller-api ............... SUCCESS [  4.802 s]
[INFO] evomaster-core ..................................... SUCCESS [01:03 min]
[INFO] evomaster-client-java-util ......................... SUCCESS [  0.201 s]
[INFO] evomaster-client-java-instrumentation .............. SUCCESS [  5.405 s]
[INFO] evomaster-client-java-controller ................... SUCCESS [ 17.698 s]
[INFO] evomaster-e2e-tests ................................ SUCCESS [  0.015 s]
[INFO] evomaster-e2e-tests-utils .......................... SUCCESS [  0.405 s]
[INFO] evomaster-e2e-tests-dropwizard-examples ............ SUCCESS [ 23.833 s]
[INFO] evomaster-e2e-tests-spring-examples ................ FAILURE [04:21 min]
[INFO] evomaster-experiments .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:18 min
[INFO] Finished at: 2018-05-14T20:13:01+07:00
[INFO] Final Memory: 79M/869M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project evomaster-e2e-tests-spring-examples: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/wisnov/workspace/EvoMaster/e2e-tests/spring-examples/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :evomaster-e2e-tests-spring-examples

**Comment by arcuri82** [comment]
yes, you need to use `-DskipTests`.
this is a bug/limitation in Surefire/Failsafe plugin, which does not fully support JUnit 5 yet (in particular, it does not support rerunning of flaky tests)

**Comment by arcuri82** [comment]
added custom support to rerun flaky tests (as unclear if and when Maven will fix it). now all tests should pass. if not, it means some flaky tests still need to be identified and handled
