### ISSUE TITLE
How do I create testcases using Black box testing

### ISSUE THREAD

**Issue by agrawalhemant5393** [EMResearch/EvoMaster#650]
I have only swagger API Link. Link is open without any login authorization. How to create test case for the same?

**Comment by arcuri82** [comment]
have you looked at the [documentation](https://github.com/EMResearch/EvoMaster/blob/master/docs/blackbox.md)?

**Comment by agrawalhemant5393** [comment]
ok. Now I got the documentation. And also got the details from the command of --help. Thanks.
