### ISSUE TITLE
Understanding the File Formats Generated in blackbox testing

### ISSUE THREAD

**Issue by agrawalhemant5393** [EMResearch/EvoMaster#652]
Hi
I used to run blackbox testing on an swaggerapi.
Multiple files have been created as shown in image:
 
![image](https://user-images.githubusercontent.com/39014040/203544140-49fb419c-944f-463b-9c01-676831e8a572.png)

How those names are defined?  As I see, each of them contains only success test. i.e. each test have 200 response code. 

I also want to know if I want to generate the other status codes testcases. Is it possible. i.e. 400 and other? 

If image is not visible then following are the file names:
EvoMaster_fault_representatives_Test.java, EvoMaster_fault_Test.java , EvoMaster_Success_Test.java

**Comment by arcuri82** [comment]
The generated tests have some documentation as comments on top of file as well. eg:

```
/**
 * This file was automatically generated by EvoMaster on 2022-10-19T12:01:24.253+02:00[Europe/Berlin]
 * <br>
 * The generated test suite contains 1 tests
 * <br>
 * Covered targets: 111
 * <br>
 * Used time: 0h 2m 13s
 * <br>
 * Needed budget for current results: 100%
 * <br>
 * This file contains one example of each category of fault. The test cases in this file are a subset of the set of test cases likely to indicate faults.
 */
```

I guess there should be more info there?

**Comment by agrawalhemant5393** [comment]
I found that. Thanks
