### ISSUE TITLE
Trying to use black box  and I'm having SSL exception

### ISSUE THREAD

**Issue by ziggy-data** [EMResearch/EvoMaster#658]
- version of EvoMaster (EM) used 1.5.0
- Running the EM with jar and using debian bullseye
- java 11 
- command-line options used to run EM:  /opt/evomaster/bin/evomaster --blackBox true --bbSwaggerUrl https://<my-ip>/v3/api-docs  --outputFormat JAVA_JUNIT_5 --maxTime 30s --outputFolder /home/dev/Documentos

I'm trying to use the evo master Black Box to test some APIs in my server but i am having an SSL Exception saying that i'm unable to find a valid certification path to requested target, is there a way to test without SSL?

error message:

* Initializing...
* [ERROR] ERROR related to the system under test: Failed to connect to https://<my-ip>/v3/api-docs: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by arcuri82** [comment]
Hi,

  you have `--bbSwaggerUrl https:///v3/api-docs `. you are trying to connect with HTTPS with a URL that has no hostname. so that exception is expected
