### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by novis135** [EMResearch/EvoMaster#662]
https://github.com/EMResearch/EvoMaster/blob/master/docs/write_driver.md
---------------------
As SpringBoot is nowadays the most common way to implement enterprise systems on the JVM, here we provide some discussions / walk-through on how to write a driver for it that extends EmbeddedSutController, using as reference the [driver for the features-service SUT in EMB](https://github.com/EMResearch/EMB/blob/master/em/embedded/rest/features-service/src/main/java/em/embedded/org/javiermf/features/EmbeddedEvoMasterController.java).
----------
Reference link is broken.

**Comment by arcuri82** [comment]
thanks for reporting this ;)

should now be fixed
