### ISSUE TITLE
What if I have login process in an API

### ISSUE THREAD

**Issue by agrawalhemant5393** [EMResearch/EvoMaster#669]
Hi
For blackbox testing, as per documentation there is authentication header need to pass for some sort of authentication. Is it server level authentication or api level.

What I want to ask is, suppose my api is not allowing me access the dashboard until I login, so I need to pass in body username and password. So login and accesstoken is mandatory if we wanted to login. So will this be capable to create such test cases for such apis for black box testing?

If yes, then can you share me some java command example for that?

**Comment by arcuri82** [comment]
some more info is now added to the documentation of BB mode
