### ISSUE TITLE
Evomaster is damaged and can't be opened - error shown for evomaster.dmg.zip (v1.5.0)

### ISSUE THREAD

**Issue by laxmikantm** [EMResearch/EvoMaster#685]
If there are stacktraces of the errors, please paste them here.

MacBook Mont 12.1

Downloaded evomaster.dmg.zip (v1.5.0) from: 
https://github.com/EMResearch/EvoMaster/releases

After unzip, tried to open the Evomaster app but following error is shown:
"“evomaster” is damaged and can’t be opened. You should move it to the Bin."

Other important info:
<img width="264" alt="Screenshot 2023-01-12 at 17 48 45" src="https://user-images.githubusercontent.com/7977484/212141373-7adf1b4c-7488-4e05-a6f3-998d2ad292f0.png">

- version of EvoMaster (EM) used 
- how EM is run (eg, if from JAR or from one of its OS installers)
- version of applicable runtimes (eg, JVM, NodeJS and .Net). For Java, can paste the output of `java --version`
- command-line options used to run EM

**Comment by laxmikantm** [comment]
@arcuri82 fyi
Thanks

**Comment by arcuri82** [comment]
Hi,
  @seran tried to install it on his Mac, and it works. As he suggested, it might be a Mac version problem. We build the `dmg` on GitHub Action under `macos-latest`, which likely points to `13.x`. It might be that installers built under `13.x` do not work for `12.x`. but we haven't fully verified it.

For the time being, you can either try to upgrade your Mac OS, or use the `jar` file

**Comment by arcuri82** [comment]
as @ZhangMan1126  suggested, on Mac 12.x you can try to run `xattr -cr /Applications/evomaster.app`. if it works, please let us know

**Comment by arcuri82** [comment]
closed as no more info was provided
