### ISSUE TITLE
Testing Pet Store API on EvoMaster

### ISSUE THREAD

**Issue by adityagoel28** [EMResearch/EvoMaster#692]
Hi, I want to test pet store API on the EvoMaster, but I can't understand where to start.
Please let me know how to start and test the API.

TIA.

**Comment by arcuri82** [comment]
Hi,
 did you look at the documentation and the introductory videos? also, what it the `pet store API`? what kind of testing are you trying? (black or white box?) etc. u need to provide a bit more info... :)

**Comment by adityagoel28** [comment]
Hey,
this is the pet store API - https://petstore.swagger.io/
I want to run this tool on this API and generate test cases for it.
I cannot find the `EmbeddedEvoMasterController.java` file to run the application.
Please help.

**Comment by arcuri82** [comment]
you cannot find `EmbeddedEvoMasterController.java` because it does not exist for it... if you want to use the tool on a new API, you need to write the `EmbeddedEvoMasterController.java` by yourself, and see the documentation on how to do it
