### ISSUE TITLE
Why only the class that is not loaded can be transformed.

### ISSUE THREAD

**Issue by flyheart** [EMResearch/EvoMaster#728]
Could you please help me to understand  why only the class that is not loaded can be transformed in the code below

https://github.com/EMResearch/EvoMaster/blob/d914a5b7501e5261da299d62793947c020db2724/client-java/instrumentation/src/main/java/org/evomaster/client/java/instrumentation/InstrumentingAgent.java#L142

**Comment by arcuri82** [comment]
hi. without that check you can end up in `LinkageError` in some special cases (if i remember correctly, it was when having circular references)

**Comment by flyheart** [comment]
tks.
