### ISSUE TITLE
WARN  o.e.c.p.rest.RestActionBuilderV3 - No path parameter for variable 'value' in /validate/{value}

### ISSUE THREAD

**Issue by abolotnov-ion** [EMResearch/EvoMaster#781]
Getting the following warning and wondering if it impacts anything. Running current version from releases jar.

The path spec for validate/{value} looks like this (under `paths` block):

```yaml
   '/validate/{value}':
    get:
      summary: validation endpoint
      tags:
        - api
      responses:
        '200':
          description: OK
        '400':
          description: Bad value in request
      operationId: get-validate
      description: submit value for validation
    parameters:
      - schema:
          type: number
        name: value
        in: path
        required: true
```

Also, when the value type is `number` why does EvoMaster hammers this API with random strings? is this by design?

**Comment by arcuri82** [comment]
hi,
  it might be an issue with your schema... the entry `parameters` does not seem to be under `get`. that might be the problem (ie `parameters` gets ignored, and so `{value}` with no info is treated as a default string)

**Comment by arcuri82** [comment]
can you indent `parameters`, and see if the problem persists?

**Comment by abolotnov-ion** [comment]
Thanks, `parameters` indentation was the issue, great catch!
