### ISSUE TITLE
Maven build failure while upgrading from JDK8 to JDK17....

### ISSUE THREAD

**Issue by Soumya9632** [EMResearch/EvoMaster#796]
[INFO] joma ............................................... SUCCESS [  0.839 s]
[INFO] framework .......................................... SUCCESS [  0.158 s]
[INFO] util ............................................... SUCCESS [  0.011 s]
[INFO] cfs ................................................ SUCCESS [  0.163 s]
[INFO] o2mlwrapper ........................................ SUCCESS [  0.046 s]
[INFO] snmp4jwrapper ...................................... SUCCESS [  0.037 s]
[INFO] omaaom ............................................. SUCCESS [  0.081 s]
[INFO] deploymentpackagecreator ........................... SUCCESS [  0.003 s]
[INFO] temp ............................................... SUCCESS [  0.002 s]
[INFO] customhttpconnector ................................ SUCCESS [  0.407 s]
[INFO] esymac ............................................. SUCCESS [  0.162 s]
[INFO] esymacstarter ...................................... FAILURE [  0.034 s]
[INFO] cnumUtility ........................................ SKIPPED
[INFO] exampleapp ......................................... SKIPPED
[INFO] nx2sfmadapter ...................................... SKIPPED
[INFO] ne3s2o2ml .......................................... SKIPPED
[INFO] ne3sassistant ...................................... SKIPPED
[INFO] omes2csv ........................................... SKIPPED
[INFO] symptomcollector ................................... SKIPPED
[INFO] tmp ................................................ SKIPPED
[INFO] customLockOutRealm ................................. SKIPPED
[INFO] SunMCFMAdapter ..................................... SKIPPED
[INFO] AF ................................................. SKIPPED
[INFO] SelfMonitoringEJBClient ............................ SKIPPED
[INFO] joma ............................................... SKIPPED
[INFO] OMAgent ............................................ SKIPPED
[INFO] NE3S ............................................... SKIPPED
[INFO] esymacStatusChecker ................................ SKIPPED
[INFO] esymacweb .......................................... SKIPPED
[INFO] Packaging  ${package.name} : Distribution .......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.432 s
[INFO] Finished at: 2023-08-30T11:40:39+05:30
[INFO] Final Memory: 28M/108M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project esymacstarter: Could not resolve dependencies for project com.nokia.joma.esymacstarter:esymacstarter:jar:DYNAMIC-SNAPSHOT: The following artifacts could not be resolved: com.nokia.joma.esymac:esymac-apiutil:jar:DYNAMIC-SNAPSHOT, com.nokia.joma.esymac:framework:jar:DYNAMIC-SNAPSHOT: Could not find artifact com.nokia.joma.esymac:esymac-apiutil:jar:DYNAMIC-SNAPSHOT at specified path /home/soumya/trunk/joma/esymacstarter/../esymac/target/esymac-apiutils.jar -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by arcuri82** [comment]
what is this? doesn't seem anything related to this repository
