### ISSUE TITLE
Missing utility scripts for replication

### ISSUE THREAD

**Issue by LucaGiamattei** [EMResearch/EvoMaster#845]
Hello,
I'm trying to replicate the (black-box) experiments related to the paper "Open Problems in Fuzzing RESTful APIs: A Comparison of Tools" with the script "arxiv_open_problems_bb.py" but I'm encountering 2 issues:

1) The generated scripts assume a folder "util" with some utility scripts, such as "bb-exp-util.jar" and "run_cmd.sh" which I cannot find. Are they generated with other scripts, or just missing?
2) With the EMB repository I'm able to generate .jar for the suts, while the generated scripts with "arxiv_open_problems_bb.py" require .sh. 

I would be grateful for any suggestion on how to replicate these experiments.
Thank you.

**Comment by arcuri82** [comment]
Hi,
 thanks for your interest in EM.
That was a particular study, with a comparisons of tools, so different settings from common set of experiments we provide guidelines to replicate too :( unfortunately, right now we don't have time to provide full replication instructions (including all built tools is hundreds of MBs). but we added missing scripts now. Hopefully that should be helpful.

**Comment by arcuri82** [comment]
Dear @LucaGiamattei ,

  thanks for trying out EvoMaster and opening an issue here. If you have 10 minutes, we would be grateful if you could fill this survey on test naming strategies #1206. We will use such information to improve EvoMaster. Thanks!
