### ISSUE TITLE
Is the installation supported for MAC. 

### ISSUE THREAD

**Issue by Smitasi** [EMResearch/EvoMaster#884]
I am using MAC machine to generate test cases for rest APIs.

In the documentation I see its only supported for windows 10.

**Comment by Smitasi** [comment]
How to [Download and Install EvoMaster on Windows 10](https://youtu.be/uh_XzGxws9o), using its .msi installer.


Is this supported for MAC machines

**Comment by arcuri82** [comment]
as stated in the documentation: `Installation: we provide installers for the main operating systems: Windows (.msi), OSX (.dmg) and Linux (.deb). We also provide an uber-fat JAR file.` 
`.msi` is for Windows. if you have a Mac, you need to use `.dmg`

**Comment by arcuri82** [comment]
Dear @Smitasi ,

  thanks for trying out EvoMaster and opening an issue here. If you have 10 minutes, we would be grateful if you could fill this survey on test naming strategies #1206. We will use such information to improve EvoMaster. Thanks!
