### ISSUE TITLE
WTSAlgorithm Crossover Bug

### ISSUE THREAD

**Issue by chrstphlbr** [EMResearch/EvoMaster#906]
Hi,

I had a look at the `xover` function in the [`WTSAlgorithm`](https://github.com/EMResearch/EvoMaster/blob/ce80ab8405148afb2c83e549f387ce3b3f3839b7/core/src/main/kotlin/org/evomaster/core/search/algorithms/WtsAlgorithm.kt#L23) and think there is a bug:
Shouldn't the indices in the `forEach` loop reference `it` instead of `i`?

Thanks and best wishes,
Christoph

**Comment by arcuri82** [comment]
hi,
 thx for reporting this issue! ;)  You are indeed correct
