### ISSUE TITLE
Heuristics calculation problem

### ISSUE THREAD

**Issue by lollipopdota** [EMResearch/EvoMaster#933]
In ExecutionTracer.java，function 'updateBranch'. Could you please confirm if the values of 'else' and 'then' are written in reverse?
<img width="702" alt="p" src="https://github.com/EMResearch/EvoMaster/assets/89899147/85f416c3-314f-4bc8-998c-a6b2b4a5fd39">

**Comment by arcuri82** [comment]
hi. yes, they are inverted on purpose, based on explanation given in the comments

**Comment by arcuri82** [comment]
Dear @lollipopdota ,

  thanks for trying out EvoMaster and opening an issue here. If you have 10 minutes, we would be grateful if you could fill this survey on test naming strategies #1206. We will use such information to improve EvoMaster. Thanks!
