### ISSUE TITLE
Setting budget on number of requests

### ISSUE THREAD

**Issue by devikasondhi** [EMResearch/EvoMaster#948]
Hi,
Is there any configuration to limit on the number of requests instead of setting maxtime while running the blackbox version of EvoMaster?

Thanks

**Comment by arcuri82** [comment]
Hi,

  yes, you can use `--maxActionEvaluations x` (replace `x` with the number of your choice) combined with `--stoppingCriterion FITNESS_EVALUATIONS`

**Comment by devikasondhi** [comment]
Thanks!

**Comment by arcuri82** [comment]
Dear @devikasondhi ,

  thanks for trying out EvoMaster and opening an issue here. If you have 10 minutes, we would be grateful if you could fill this survey on test naming strategies #1206. We will use such information to improve EvoMaster. Thanks!
