### ISSUE TITLE
Blackbox for JDK later than 11 not working

### ISSUE THREAD

**Issue by henning410** [EMResearch/EvoMaster#950]
```
* EvoMaster version: 3.0.0
* It looks like you are running EvoMaster with JDK 17+, but did not setup '--add-opens'. Unfortunately, Java has broken a lot of
backward compatibility in its recent versions. You should use the EvoMaster OS installers (e.g., .msi and .dmg files). 
If you want to use the JAR file directly, you need to either upgrade to JDK 8 or 11, or setup --add-opens JVM option manually
on the command-line  (or in the JDK_JAVA_OPTIONS environment variable)
```

Other important info:
- version of EvoMaster (EM) used: **3.0.0**
- how EM is run (eg, if from JAR or from one of its OS installers): **from JAR**
- version of applicable runtimes (eg, JVM, NodeJS and .Net). For Java, can paste the output of `java --version`: **openjdk 17.0.10 2024-01-16**
- command-line options used to run EM: 
```
java -jar evomaster.jar  --blackBox true --bbSwaggerUrl http://localhost:3000/api-json --outputFormat JAVA_JUNIT_4 --maxTime 30s --ratePerMinute 60 
```

**Comment by henning410** [comment]
Got it working by using the Linux Installer. Maybe this can be better explained in https://github.com/EMResearch/EvoMaster/blob/master/docs/blackbox.md like already did for whitebox-testing.

**Comment by arcuri82** [comment]
thanks for your interest in EvoMaster.
we will update the documentation to better clarify this.

**Comment by arcuri82** [comment]
see the new paragraph `Issues with JDKs Above 8` in the linked documentation. Would that be enough? or do you think some more details are needed? thx!

**Comment by henning410** [comment]
Wow, that was fast. Perfect now I would say :)
