### ISSUE TITLE
Wrong naming for generated jest files

### ISSUE THREAD

**Issue by henning410** [EMResearch/EvoMaster#951]
According to jest, test files are searched based on the naming: 
`testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 0 matches`

If I got it correctly, the files currently are generated using the schema `EvoMaster_XX_Test.js`. 
So the generated files needs to be renamed manually to get them executed using jest. Maybe the automated naming can be changed to `EvoMaster_XX.test.js`. Or store the files automatically in folder \_\_tests__. But as user I would expect naming as `EvoMaster_XX.test.js`

Other important info:
- version of EvoMaster (EM) used: **3.0.0**
- how EM is run (eg, if from JAR or from one of its OS installers): **OS Installer**
- version of applicable runtimes (eg, JVM, NodeJS and .Net). For Java, can paste the output of `java --version`: **openjdk 17.0.10 2024-01-16**
- command-line options used to run EM
`/opt/evomaster/bin/evomaster  --blackBox true --bbSwaggerUrl http://localhost:3000/api-json --outputFormat JS_JEST --maxTime 30s --ratePerMinute 60 --writeStatistics true`

**Comment by arcuri82** [comment]
Dear @henning410 ,

  thanks for trying out EvoMaster and opening an issue here. If you have 10 minutes, we would be grateful if you could fill this survey on test naming strategies #1206. We will use such information to improve EvoMaster. Thanks!
